### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
#creo un ciclo che restituisce la lista i caratteri di una stringa
a = "Python>R"
lettere = []
for lettera in a:
    lettere.append(lettera)

lettere = [lettera for lettera in a]


#creo un ciclo che restituisce la lista dei numeri da 1 a 19
num = []
for n in range(1,20):
    num.append(n)

num = [n for n in range(1,20)]

#creo un ciclo che restituisce una lista di liste dove le liste interne sono i caratteri di una parola di una stringa
stringa = "Python è meglio di R"
frase = []
parola = []
for parole in stringa.split(" "):
    for lettera in parole:
        parola.append(lettera)
    frase.append(parola)
    parola = []

frase = [[lettera for lettera in parola] for parola in stringa.split(" ")]


[['P', 'y', 't', 'h', 'o', 'n'], ['è'], ['m', 'e', 'g', 'l', 'i', 'o'], ['d', 'i'], ['R']]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [2]:
import numpy as np
def n_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

a = np.array([2,3,5,7])
if len(a) == a.size:
    print(f"len e size danno lo stesso risultato che è {len(a)}")

n_primi = np.array([x for x in range(1, 11) if n_primo(x)])
print(n_primi)
#il tipo di dato sarà intero
print(n_primi.dtype)


len e size danno lo stesso risultato che è 4
[2 3 5 7]
int64


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [17]:
a = np.array([x for x in range(1,5)])
b = np.array(a[2:3])
c = np.array(a[::-1])
print(a/c)
print(a)
print(b)
print(c)

a=[x for x in range(1,5)]
b=a[2:3]
c=a[::-1]
a_diviso_c = [(a[i]/c[i]) for i in range(0,len(a))]
print(a_diviso_c)
print(a)
print(c)

[0.25       0.66666667 1.5        4.        ]
[1 2 3 4]
[3]
[4 3 2 1]
[0.25, 0.6666666666666666, 1.5, 4.0]
[1, 2, 3, 4]
[4, 3, 2, 1]
